all:
	g++ -std=c++20 -Ofast -flto bits.cpp board.cpp evaluation.cpp hashKey.cpp main.cpp moveGenerator.cpp perft.cpp search.cpp state.cpp staticExchangeEvaluation.cpp table.cpp updateState.cpp -o ChandraChess -Bstatic
	./ChandraChess